import {
  Table,
  ChakraProvider,
  Thead,
  Th,
  Tr,
  Tbody,
  Td,
  Box,
} from "@chakra-ui/react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Line, ResponsiveLine } from "@nivo/line";

const data = [
  {
    id: "japan",
    color: "hsl(326, 70%, 50%)",
    data: [
      {
        x: "plane",
        y: 206,
      },
      {
        x: "helicopter",
        y: 165,
      },
      {
        x: "boat",
        y: 229,
      },
      {
        x: "train",
        y: 21,
      },
      {
        x: "subway",
        y: 85,
      },
      {
        x: "bus",
        y: 25,
      },
      {
        x: "car",
        y: 222,
      },
      {
        x: "moto",
        y: 134,
      },
      {
        x: "bicycle",
        y: 173,
      },
      {
        x: "horse",
        y: 268,
      },
      {
        x: "skateboard",
        y: 220,
      },
      {
        x: "others",
        y: 72,
      },
    ],
  },
  {
    id: "france",
    color: "hsl(131, 70%, 50%)",
    data: [
      {
        x: "plane",
        y: 122,
      },
      {
        x: "helicopter",
        y: 91,
      },
      {
        x: "boat",
        y: 123,
      },
      {
        x: "train",
        y: 63,
      },
      {
        x: "subway",
        y: 101,
      },
      {
        x: "bus",
        y: 239,
      },
      {
        x: "car",
        y: 77,
      },
      {
        x: "moto",
        y: 173,
      },
      {
        x: "bicycle",
        y: 32,
      },
      {
        x: "horse",
        y: 66,
      },
      {
        x: "skateboard",
        y: 213,
      },
      {
        x: "others",
        y: 187,
      },
    ],
  },
  {
    id: "us",
    color: "hsl(305, 70%, 50%)",
    data: [
      {
        x: "plane",
        y: 11,
      },
      {
        x: "helicopter",
        y: 105,
      },
      {
        x: "boat",
        y: 296,
      },
      {
        x: "train",
        y: 34,
      },
      {
        x: "subway",
        y: 140,
      },
      {
        x: "bus",
        y: 135,
      },
      {
        x: "car",
        y: 237,
      },
      {
        x: "moto",
        y: 104,
      },
      {
        x: "bicycle",
        y: 73,
      },
      {
        x: "horse",
        y: 41,
      },
      {
        x: "skateboard",
        y: 158,
      },
      {
        x: "others",
        y: 105,
      },
    ],
  },
  {
    id: "germany",
    color: "hsl(263, 70%, 50%)",
    data: [
      {
        x: "plane",
        y: 110,
      },
      {
        x: "helicopter",
        y: 287,
      },
      {
        x: "boat",
        y: 141,
      },
      {
        x: "train",
        y: 225,
      },
      {
        x: "subway",
        y: 64,
      },
      {
        x: "bus",
        y: 84,
      },
      {
        x: "car",
        y: 131,
      },
      {
        x: "moto",
        y: 288,
      },
      {
        x: "bicycle",
        y: 161,
      },
      {
        x: "horse",
        y: 255,
      },
      {
        x: "skateboard",
        y: 132,
      },
      {
        x: "others",
        y: 24,
      },
    ],
  },
  {
    id: "norway",
    color: "hsl(213, 70%, 50%)",
    data: [
      {
        x: "plane",
        y: 170,
      },
      {
        x: "helicopter",
        y: 48,
      },
      {
        x: "boat",
        y: 65,
      },
      {
        x: "train",
        y: 261,
      },
      {
        x: "subway",
        y: 286,
      },
      {
        x: "bus",
        y: 242,
      },
      {
        x: "car",
        y: 20,
      },
      {
        x: "moto",
        y: 219,
      },
      {
        x: "bicycle",
        y: 204,
      },
      {
        x: "horse",
        y: 231,
      },
      {
        x: "skateboard",
        y: 224,
      },
      {
        x: "others",
        y: 163,
      },
    ],
  },
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ROBOSERVICE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {/* insert navbar */}
        <Table>
          <Thead>
            <Tr>
              <Th></Th>
              <Th>Executions</Th>
              <Th>Passes</Th>
              <Th>Executions</Th>
              <Th>Passes</Th>
            </Tr>
          </Thead>
          <Tbody>
            <Tr>
              <Td>Test 1</Td>
              <Td>100</Td>
              <Td>100</Td>
              <Td>100</Td>
              <Td>100</Td>
            </Tr>
          </Tbody>
        </Table>
        <Box className="test" h="40vh">
          <ResponsiveLine
            data={data}
            margin={{ top: 50, right: 110, bottom: 50, left: 60 }}
            xScale={{ type: "point" }}
            yScale={{
              type: "linear",
              min: "auto",
              max: "auto",
              stacked: true,
              reverse: false,
            }}
            yFormat=" >-.2f"
            axisTop={null}
            axisRight={null}
            axisBottom={{
              orient: "bottom",
              tickSize: 5,
              tickPadding: 5,
              tickRotation: 0,
              legend: "transportation",
              legendOffset: 36,
              legendPosition: "middle",
            }}
            axisLeft={{
              orient: "left",
              tickSize: 5,
              tickPadding: 5,
              tickRotation: 0,
              legend: "count",
              legendOffset: -40,
              legendPosition: "middle",
            }}
            pointSize={10}
            pointColor={{ theme: "background" }}
            pointBorderWidth={2}
            pointBorderColor={{ from: "serieColor" }}
            pointLabelYOffset={-12}
            useMesh={true}
            legends={[
              {
                anchor: "bottom-right",
                direction: "column",
                justify: false,
                translateX: 100,
                translateY: 0,
                itemsSpacing: 0,
                itemDirection: "left-to-right",
                itemWidth: 80,
                itemHeight: 20,
                itemOpacity: 0.75,
                symbolSize: 12,
                symbolShape: "circle",
                symbolBorderColor: "rgba(0, 0, 0, .5)",
                effects: [
                  {
                    on: "hover",
                    style: {
                      itemBackground: "rgba(0, 0, 0, .03)",
                      itemOpacity: 1,
                    },
                  },
                ],
              },
            ]}
          />
        </Box>
    </div>
  );
}
